version = 0.1

[default.deploy.parameters]
stack_name = "fintrack-ai-poc"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = true
confirm_changeset = false
profile = "fintrack"

[default.global.parameters]
region = "eu-west-1"
